from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('personal-information/', views.PersonalInformationView.as_view(), name='personal-information'),
    path('contacts/<int:pk>/update/', views.ContactUpdateView.as_view(), name='contact_update'),
    path('skills/', views.SkillListView.as_view(), name='skill_list'),
    path('skills/<int:pk>/', views.SkillDetailView.as_view(), name='skill_detail'),
    path('skills/create/', views.SkillCreateView.as_view(), name='skill_create'),
    path('skills/<int:pk>/update/', views.SkillUpdateView.as_view(), name='skill_update'),
    path('skills/<int:pk>/delete/', views.SkillDeleteView.as_view(), name='skill_delete'),
    path('services/', views.ServiceListView.as_view(), name='service_list'),
    path('services/<int:pk>/', views.ServiceDetailView.as_view(), name='service_detail'),
    path('services/create/', views.ServiceCreateView.as_view(), name='service_create'),
    path('services/<int:pk>/update/', views.ServiceUpdateView.as_view(), name='service_update'),
    path('services/<int:pk>/delete/', views.ServiceDeleteView.as_view(), name='service_delete'),
    path('facts/', views.FactListView.as_view(), name='fact_list'),
    path('facts/<int:pk>/', views.FactDetailView.as_view(), name='fact_detail'),
    path('facts/create/', views.FactCreateView.as_view(), name='fact_create'),
    path('facts/<int:pk>/update/', views.FactUpdateView.as_view(), name='fact_update'),
    path('facts/<int:pk>/delete/', views.FactDeleteView.as_view(), name='fact_delete'),
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    path('projects/<int:pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/create/', views.ProjectCreateView.as_view(), name='project_create'),
    path('projects/<int:pk>/update/', views.ProjectUpdateView.as_view(), name='project_update'),
    path('projects/<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('testimonies/', views.TestimonyListView.as_view(), name='testimony_list'),
    path('testimonies/<int:pk>/', views.TestimonyDetailView.as_view(), name='testimony_detail'),
    path('testimonies/create/', views.TestimonyCreateView.as_view(), name='testimony_create'),
    path('testimonies/<int:pk>/update/', views.TestimonyUpdateView.as_view(), name='testimony_update'),
    path('testimonies/<int:pk>/delete/', views.TestimonyDeleteView.as_view(), name='testimony_delete'),
    path('summary/<int:pk>/update/', views.SummaryUpdateView.as_view(), name='summary_update'),
    path('education/', views.EducationListView.as_view(), name='education_list'),
    path('education/<int:pk>/', views.EducationDetailView.as_view(), name='education_detail'),
    path('education/create/', views.EducationCreateView.as_view(), name='education_create'),
    path('education/<int:pk>/update/', views.EducationUpdateView.as_view(), name='education_update'),
    path('education/<int:pk>/delete/', views.EducationDeleteView.as_view(), name='education_delete'),
    path('experience/', views.ExperienceListView.as_view(), name='experience_list'),
    path('experience/<int:pk>/', views.ExperienceDetailView.as_view(), name='experience_detail'),
    path('experience/create/', views.ExperienceCreateView.as_view(), name='experience_create'),
    path('experience/<int:pk>/update/', views.ExperienceUpdateView.as_view(), name='experience_update'),
    path('experience/<int:pk>/delete/', views.ExperienceDeleteView.as_view(), name='experience_delete'),
    path('submit/', views.ContactFormSubmitView.as_view(), name='contact_form_submit'),
    path('messages/', views.MessagesListView.as_view(), name='messages_list'),
]
